name: offline_ai_expense_tracker
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # AI
  # Force upgrade to the latest version that supports .prompt() stream
  llama_cpp_dart: ^0.1.2+1
  
  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  
  # Utils
  path_provider: ^2.0.15
  provider: ^6.1.1
  intl: ^0.19.0
  window_manager: ^0.5.1
  table_calendar: ^3.0.9

  # Slip Scanner
  photo_manager: ^3.0.0
  flutter_tesseract_ocr: ^0.4.30
  shared_preferences: ^2.2.2
  permission_handler: ^12.0.1
  device_info_plus: ^12.3.0
  fl_chart: ^1.1.1
  image: ^4.5.4
  image_picker: ^1.0.7
  image_cropper: ^8.0.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter_native_splash:
  color: "#0F172A"
  image: assets/images/app_logo.png
  android_12:
    image: assets/images/app_logo.png
    color: "#0F172A"

flutter:
  uses-material-design: true
  assets:
    - assets/models/model-unsloth21.Q4_0.gguf
    - assets/tessdata/
    - assets/tessdata_config.json
